### ISSUE TITLE
Create Code Analysis with SonarCloud

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#500]
SonarCloud is available for free here: https://github.com/apps/sonarcloud

Someone with access to the OWASP org needs to configure it for us.

Once it's configured we need to;

1. Create a user authentication token for the account on SonarCloud.
2.[ Encrypt this token](https://docs.travis-ci.com/user/encryption-keys/#usage) `travis encrypt abcdef0123456789 --pro` 
3. Before pushing get the OWASP organisation key for SonarCloud
4. Create a sonar-project.properties file with the following lines;

```
sonar-project.properties
# must be unique in a given SonarQube instance
sonar.projectKey=<owaspSecurityShepherd or whatever it is>
```

Edit the `.travis-ci.yaml` and add a stage `analysis`

```
- stage: analysis
      name: "Code Analysis"
      services: 
        - mysql
        - docker
      language: java
      addons: 
        sonarcloud:
          organization: "owasp (or whatever)"
          token:
              secure: "base64 key"
      script: "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ismisepaul_SecurityShepherd -Pdocker -DmongoDocker -B"
    
```
see here https://github.com/ismisepaul/SecurityShepherd/blob/dev/.travis.yml 

Example of current code analysis https://sonarcloud.io/dashboard?id=ismisepaul_SecurityShepherd
